import type {
  ThemeConfig,
  ThemeName,
  ThemeRegistry,
} from "@portfolio/frontend/src/types/theme";

export const themes: ThemeRegistry = {
  default: {
    name: "Default Dark",
    colors: {
      bg: "#0a0a0a",
      text: "#e5e5e5",
      accent: "#00ff41",
      muted: "#666666",
      border: "#333333",
      success: "#00ff41",
      error: "#ff4444",
      warning: "#ffaa00",
      info: "#00aaff",
      prompt: "#00ff41",
    },
    description: "Classic terminal dark theme",
  },
  matrix: {
    name: "Matrix",
    colors: {
      bg: "#000000",
      text: "#00ff41",
      accent: "#00ff41",
      muted: "#008f11",
      border: "#00ff41",
      success: "#00ff41",
      error: "#ff0000",
      warning: "#ffff00",
      info: "#00ffff",
      prompt: "#00ff41",
    },
    description: "Green on black Matrix-style theme",
  },
  cyberpunk: {
    name: "Cyberpunk",
    colors: {
      bg: "#0f0f23",
      text: "#ff00ff",
      accent: "#00ffff",
      muted: "#666699",
      border: "#ff00ff",
      success: "#00ff00",
      error: "#ff0040",
      warning: "#ffff00",
      info: "#00ffff",
      prompt: "#ff00ff",
    },
    description: "Neon cyberpunk aesthetic",
  },
  dracula: {
    name: "Dracula",
    colors: {
      bg: "#282a36",
      text: "#f8f8f2",
      accent: "#bd93f9",
      muted: "#6272a4",
      border: "#44475a",
      success: "#50fa7b",
      error: "#ff5555",
      warning: "#f1fa8c",
      info: "#8be9fd",
      prompt: "#bd93f9",
    },
    description: "Popular Dracula color scheme",
  },
  monokai: {
    name: "Monokai",
    colors: {
      bg: "#272822",
      text: "#f8f8f2",
      accent: "#a6e22e",
      muted: "#75715e",
      border: "#49483e",
      success: "#a6e22e",
      error: "#f92672",
      warning: "#fd971f",
      info: "#66d9ef",
      prompt: "#a6e22e",
    },
    description: "Classic Monokai theme",
  },
  solarized: {
    name: "Solarized Dark",
    colors: {
      bg: "#002b36",
      text: "#839496",
      accent: "#268bd2",
      muted: "#586e75",
      border: "#073642",
      success: "#859900",
      error: "#dc322f",
      warning: "#b58900",
      info: "#2aa198",
      prompt: "#268bd2",
    },
    description: "Solarized dark color scheme",
  },
  gruvbox: {
    name: "Gruvbox",
    colors: {
      bg: "#282828",
      text: "#ebdbb2",
      accent: "#fabd2f",
      muted: "#928374",
      border: "#3c3836",
      success: "#b8bb26",
      error: "#fb4934",
      warning: "#fe8019",
      info: "#83a598",
      prompt: "#fabd2f",
    },
    description: "Retro groove color scheme",
  },
  nord: {
    name: "Nord",
    colors: {
      bg: "#2e3440",
      text: "#d8dee9",
      accent: "#88c0d0",
      muted: "#4c566a",
      border: "#3b4252",
      success: "#a3be8c",
      error: "#bf616a",
      warning: "#ebcb8b",
      info: "#5e81ac",
      prompt: "#88c0d0",
    },
    description: "Arctic, north-bluish color palette",
  },
  tokyo: {
    name: "Tokyo Night",
    colors: {
      bg: "#1a1b26",
      text: "#c0caf5",
      accent: "#7aa2f7",
      muted: "#565f89",
      border: "#292e42",
      success: "#9ece6a",
      error: "#f7768e",
      warning: "#e0af68",
      info: "#7dcfff",
      prompt: "#7aa2f7",
    },
    description: "Tokyo Night theme",
  },
  onedark: {
    name: "One Dark",
    colors: {
      bg: "#282c34",
      text: "#abb2bf",
      accent: "#61afef",
      muted: "#5c6370",
      border: "#3e4451",
      success: "#98c379",
      error: "#e06c75",
      warning: "#e5c07b",
      info: "#56b6c2",
      prompt: "#61afef",
    },
    description: "Atom One Dark theme",
  },
  catppuccin: {
    name: "Catppuccin",
    colors: {
      bg: "#1e1e2e",
      text: "#cdd6f4",
      accent: "#cba6f7",
      muted: "#6c7086",
      border: "#313244",
      success: "#a6e3a1",
      error: "#f38ba8",
      warning: "#f9e2af",
      info: "#89b4fa",
      prompt: "#cba6f7",
    },
    description: "Soothing pastel theme",
  },
  synthwave: {
    name: "Synthwave",
    colors: {
      bg: "#2a0845",
      text: "#f92aad",
      accent: "#f97e72",
      muted: "#848bbd",
      border: "#495495",
      success: "#72f1b8",
      error: "#fe4450",
      warning: "#fede5d",
      info: "#36f9f6",
      prompt: "#f97e72",
    },
    description: "Retro synthwave aesthetic",
  },
  vscode: {
    name: "VS Code Dark",
    colors: {
      bg: "#1e1e1e",
      text: "#d4d4d4",
      accent: "#007acc",
      muted: "#808080",
      border: "#2d2d30",
      success: "#4ec9b0",
      error: "#f44747",
      warning: "#ffcc02",
      info: "#9cdcfe",
      prompt: "#007acc",
    },
    description: "VS Code default dark theme",
  },
  github: {
    name: "GitHub Dark",
    colors: {
      bg: "#0d1117",
      text: "#c9d1d9",
      accent: "#58a6ff",
      muted: "#8b949e",
      border: "#30363d",
      success: "#3fb950",
      error: "#f85149",
      warning: "#d29922",
      info: "#79c0ff",
      prompt: "#58a6ff",
    },
    description: "GitHub dark theme",
  },
  terminal: {
    name: "Classic Terminal",
    colors: {
      bg: "#000000",
      text: "#00ff00",
      accent: "#00ff00",
      muted: "#008000",
      border: "#00ff00",
      success: "#00ff00",
      error: "#ff0000",
      warning: "#ffff00",
      info: "#00ffff",
      prompt: "#00ff00",
    },
    description: "Classic green terminal",
  },
  hacker: {
    name: "Hacker",
    colors: {
      bg: "#000000",
      text: "#00ff00",
      accent: "#ff0000",
      muted: "#008000",
      border: "#00ff00",
      success: "#00ff00",
      error: "#ff0000",
      warning: "#ffff00",
      info: "#00ffff",
      prompt: "#ff0000",
    },
    description: "Hacker-style terminal",
  },
  neon: {
    name: "Neon",
    colors: {
      bg: "#0a0a0a",
      text: "#ff10f0",
      accent: "#00ffff",
      muted: "#ff1493",
      border: "#ff10f0",
      success: "#00ff00",
      error: "#ff0040",
      warning: "#ffff00",
      info: "#00ffff",
      prompt: "#00ffff",
    },
    description: "Bright neon colors",
  },
  retro: {
    name: "Retro",
    colors: {
      bg: "#2b1810",
      text: "#ffb000",
      accent: "#ff6600",
      muted: "#cc8800",
      border: "#ff6600",
      success: "#00cc00",
      error: "#cc0000",
      warning: "#ffcc00",
      info: "#0099cc",
      prompt: "#ff6600",
    },
    description: "Retro amber terminal",
  },
  minimal: {
    name: "Minimal",
    colors: {
      bg: "#fafafa",
      text: "#333333",
      accent: "#0066cc",
      muted: "#666666",
      border: "#e0e0e0",
      success: "#00aa00",
      error: "#cc0000",
      warning: "#ff8800",
      info: "#0088cc",
      prompt: "#0066cc",
    },
    description: "Clean minimal light theme",
  },
  ocean: {
    name: "Ocean",
    colors: {
      bg: "#0f1419",
      text: "#b3b1ad",
      accent: "#39bae6",
      muted: "#626a73",
      border: "#1f2430",
      success: "#7fd962",
      error: "#ff3333",
      warning: "#ffb454",
      info: "#59c2ff",
      prompt: "#39bae6",
    },
    description: "Deep ocean blue theme",
  },
  forest: {
    name: "Forest",
    colors: {
      bg: "#1b2b1b",
      text: "#a7c080",
      accent: "#83c092",
      muted: "#7a8478",
      border: "#2d3d2d",
      success: "#a7c080",
      error: "#e67e80",
      warning: "#dbbc7f",
      info: "#7fbbb3",
      prompt: "#83c092",
    },
    description: "Forest green theme",
  },
};

export const defaultTheme: ThemeName = "default";

export const getSortedThemeNames = (): ThemeName[] => {
  return Object.keys(themes).sort() as ThemeName[];
};

export const getThemeConfig = (themeName: ThemeName): ThemeConfig => {
  return themes[themeName] || themes[defaultTheme];
};

export const validateTheme = (themeName: string): themeName is ThemeName => {
  return Object.keys(themes).includes(themeName);
};

export const getThemePreview = (themeName: ThemeName): string => {
  const config = themes[themeName];
  if (!config) return "";

  return [
    `🎨 ${config.name}`,
    `Background: ${config.colors.bg}`,
    `Text: ${config.colors.text}`,
    `Accent: ${config.colors.accent}`,
    config.description || "",
  ].join(" | ");
};
